from __future__ import annotations

import html
import logging
import re
from dataclasses import asdict, dataclass
from datetime import date, datetime
from typing import Sequence

import arxiv
import requests
from bs4 import BeautifulSoup

logger = logging.getLogger(__name__)

HF_PAPERS_URL = "https://huggingface.co/papers"
ARXIV_ABS_URL = "https://arxiv.org/abs/{}"

MONTHS = {
    "Jan": 1, "Feb": 2, "Mar": 3, "Apr": 4,
    "May": 5, "Jun": 6, "Jul": 7, "Aug": 8,
    "Sep": 9, "Oct": 10, "Nov": 11, "Dec": 12,
}


@dataclass(frozen=True)
class Paper:
    id: str
    title: str
    abstract: str
    authors: list[str]
    url: str
    published_date: str

    def to_dict(self) -> dict:
        return asdict(self)


def _coerce_date(value: date | datetime | str | None) -> date | None:
    if value is None:
        return None
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    return date.fromisoformat(value)


def _clean_text(value: str | None) -> str:
    return re.sub(r"\s+", " ", html.unescape(value or "")).strip()


def _extract_arxiv_id(text: str | None) -> str | None:
    if not text:
        return None
    m = re.search(r"(\d{4}\.\d{4,5})(?:v\d+)?", text)
    if m:
        return m.group(1)
    m = re.search(r"arxiv:(\d{4}\.\d{4,5})(?:v\d+)?", text, flags=re.IGNORECASE)
    if m:
        return m.group(1)
    return None


def _parse_hf_published_date(lines: list[str], fallback: date) -> str:
    for line in lines:
        m = re.search(r"Published on\s+([A-Za-z]{3})\s+(\d{1,2})(?:,\s*(\d{4}))?", line)
        if m:
            month = MONTHS.get(m.group(1), fallback.month)
            day = int(m.group(2))
            year = int(m.group(3) or fallback.year)
            return date(year, month, day).isoformat()
    return fallback.isoformat()


def _fetch_hf_paper_detail(
    session: requests.Session,
    paper_id: str,
    title_fallback: str,
    fallback_date: date,
) -> Paper:
    url = f"{HF_PAPERS_URL}/{paper_id}"
    resp = session.get(url, timeout=30)
    resp.raise_for_status()

    soup = BeautifulSoup(resp.text, "html.parser")
    title = _clean_text(soup.find("h1").get_text(" ", strip=True) if soup.find("h1") else title_fallback)

    full_text = soup.get_text("\n", strip=True)
    lines = [ln.strip() for ln in full_text.splitlines() if ln.strip()]

    published_date = _parse_hf_published_date(lines, fallback_date)

    authors: list[str] = []
    author_idx = next((i for i, ln in enumerate(lines) if ln.lower().startswith("authors")), -1)
    abstract_idx = next((i for i, ln in enumerate(lines) if ln.lower() == "abstract"), -1)

    if author_idx != -1 and abstract_idx != -1 and abstract_idx > author_idx:
        author_lines = lines[author_idx + 1 : abstract_idx]
        raw_authors = ", ".join(author_lines)
        authors = [a.strip(" ,") for a in raw_authors.split(",") if a.strip(" ,")]

    abstract = ""
    if abstract_idx != -1:
        stop_markers = {
            "generated by",
            "view arxiv page",
            "view pdf",
            "community",
            "copy markdown",
            "paper submitter",
            "models citing this paper",
            "datasets citing this paper",
            "spaces citing this paper",
            "collections including this paper",
        }
        abstract_lines: list[str] = []
        for ln in lines[abstract_idx + 1 :]:
            low = ln.lower()
            if low in stop_markers or low.startswith("## ") or low.startswith("submitted by"):
                break
            if low.startswith("upvote "):
                continue
            abstract_lines.append(ln)
        abstract = _clean_text(" ".join(abstract_lines))

    arxiv_id = _extract_arxiv_id(full_text)
    paper_url = ARXIV_ABS_URL.format(arxiv_id) if arxiv_id else url
    paper_key = arxiv_id or paper_id

    return Paper(
        id=paper_key,
        title=title,
        abstract=abstract,
        authors=authors,
        url=paper_url,
        published_date=published_date,
    )


def fetch_arxiv(
    categories: Sequence[str],
    max_results: int,
    date_from: date | datetime | str | None,
) -> list[Paper]:
    if max_results <= 0:
        return []

    categories = [c.strip() for c in categories if c and c.strip()]
    if not categories:
        return []

    since = _coerce_date(date_from)

    query = " OR ".join(f"cat:{cat}" for cat in categories)
    search = arxiv.Search(
        query=query,
        max_results=max_results,
        sort_by=arxiv.SortCriterion.SubmittedDate,
        sort_order=arxiv.SortOrder.Descending,
    )

    client = arxiv.Client(page_size=min(100, max_results))
    papers: list[Paper] = []

    for result in client.results(search):
        published = result.published.date()
        if since and published < since:
            continue

        paper_id = _extract_arxiv_id(getattr(result, "entry_id", None)) or result.get_short_id()
        if not paper_id:
            continue

        authors = [a.name for a in result.authors]
        papers.append(
            Paper(
                id=paper_id,
                title=_clean_text(result.title),
                abstract=_clean_text(result.summary),
                authors=authors,
                url=result.entry_id,
                published_date=published.isoformat(),
            )
        )

        if len(papers) >= max_results:
            break

    return papers


def fetch_huggingface_daily(date_value: date | datetime | str) -> list[Paper]:
    day = _coerce_date(date_value)
    if day is None:
        raise ValueError("date_value is required")

    session = requests.Session()
    session.headers.update(
        {
            "User-Agent": "PaperLead/1.0 (+https://huggingface.co/papers)",
            "Accept": "text/html,application/xhtml+xml",
        }
    )

    resp = session.get(HF_PAPERS_URL, params={"date": day.isoformat()}, timeout=30)
    resp.raise_for_status()

    soup = BeautifulSoup(resp.text, "html.parser")

    seen_ids: set[str] = set()
    papers: list[Paper] = []

    for a in soup.select('a[href^="/papers/"]'):
        href = a.get("href", "")
        m = re.fullmatch(r"/papers/(\d{4}\.\d{4,5}(?:v\d+)?)", href)
        if not m:
            continue

        paper_id = m.group(1)
        base_id = _extract_arxiv_id(paper_id) or paper_id
        if base_id in seen_ids:
            continue
        seen_ids.add(base_id)

        title_fallback = _clean_text(a.get_text(" ", strip=True))
        try:
            paper = _fetch_hf_paper_detail(session, paper_id=paper_id, title_fallback=title_fallback, fallback_date=day)
            papers.append(paper)
        except Exception as exc:
            logger.warning("Failed to fetch HF paper %s: %s", paper_id, exc)
            papers.append(
                Paper(
                    id=base_id,
                    title=title_fallback or paper_id,
                    abstract="",
                    authors=[],
                    url=f"{HF_PAPERS_URL}/{paper_id}",
                    published_date=day.isoformat(),
                )
            )

    return papers


def fetch_all(
    categories: Sequence[str],
    max_results: int,
    date_from: date | datetime | str | None,
    hf_date: date | datetime | str | None = None,
) -> list[Paper]:
    arxiv_papers = fetch_arxiv(categories=categories, max_results=max_results, date_from=date_from)
    hf_day = _coerce_date(hf_date) or _coerce_date(date_from) or date.today()
    hf_papers = fetch_huggingface_daily(hf_day)

    merged: dict[str, Paper] = {p.id: p for p in arxiv_papers}
    for p in hf_papers:
        merged.setdefault(p.id, p)
    return list(merged.values())
